# vim: set ft=yaml:
---
version: '2.3'

# ------------------------------------------------------------
# Yaml Default
# ------------------------------------------------------------

###
### Default PHP-FPM config
###
x-app: &default-php
  restart: unless-stopped
  env_file:
    - ./.env
  environment:
    # Debug/Logging
    - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT:-2}
    - DOCKER_LOGS=1
    # Enable/Disable PHP Modules
    - ENABLE_MODULES=${PHP_MODULES_ENABLE}
    - DISABLE_MODULES=${PHP_MODULES_DISABLE}
    # Mail-catching
    - ENABLE_MAIL=${PHP_MAIL_CATCH_ALL:-2}
  volumes:
    - ${DEVILBOX_PATH}/cfg/php-startup-${PHP_SERVER}:/startup.1.d:rw${MOUNT_OPTIONS}
    - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
  dns:
    - 172.16.238.100
  depends_on:
    - bind


# ------------------------------------------------------------
# Services
# ------------------------------------------------------------
services:
  mongo:
    image: alpine
    entrypoint: []
  pgsql:
    image: alpine
    entrypoint: []
  redis:
    image: alpine
    entrypoint: []
    command: ''
  memcd:
    image: alpine
    entrypoint: []

  # php70:
  #   <<: *default-php
  #   image: devilbox/php-fpm:7.0-work-0.150
  #   hostname: php70
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.204
  #   volumes:
  #     # Specific volumes
  #     - ${DEVILBOX_PATH}/cfg/php-ini-7.0:/etc/php-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-fpm-7.0:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-startup-7.0:/startup.1.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/log/php-fpm-7.0:/var/log/php:rw${MOUNT_OPTIONS}
  #     # Generic volumes
  #     - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
  #     - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
  #     - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  php71:
    <<: *default-php
    image: devilbox/php-fpm:7.1-work-0.150
    hostname: php71
    networks:
      app_net:
        ipv4_address: 172.16.238.205
    volumes:
      # Specific volumes
      - ${DEVILBOX_PATH}/cfg/php-ini-7.1:/etc/php-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-fpm-7.1:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-startup-7.1:/startup.1.d:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/log/php-fpm-7.1:/var/log/php:rw${MOUNT_OPTIONS}
      # Generic volumes
      - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
      - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
      - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  php72:
    <<: *default-php
    image: devilbox/php-fpm:7.2-work-0.150
    hostname: php72
    networks:
      app_net:
        ipv4_address: 172.16.238.206
    volumes:
      # Specific volumes
      - ${DEVILBOX_PATH}/cfg/php-ini-7.2:/etc/php-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-fpm-7.2:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-startup-7.2:/startup.1.d:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/log/php-fpm-7.2:/var/log/php:rw${MOUNT_OPTIONS}
      # Generic volumes
      - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
      - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
      - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  php73:
    <<: *default-php
    image: devilbox/php-fpm:7.3-work-0.150
    hostname: php73
    networks:
      app_net:
        ipv4_address: 172.16.238.207
    volumes:
      # Specific volumes
      - ${DEVILBOX_PATH}/cfg/php-ini-7.3:/etc/php-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-fpm-7.3:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-startup-7.3:/startup.1.d:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/log/php-fpm-7.3:/var/log/php:rw${MOUNT_OPTIONS}
      # Generic volumes
      - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
      - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
      - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  # php74:
  #   <<: *default-php
  #   image: devilbox/php-fpm:7.4-work-0.150
  #   hostname: php74
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.208
  #   volumes:
  #     # Specific volumes
  #     - ${DEVILBOX_PATH}/cfg/php-ini-7.4:/etc/php-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-fpm-7.4:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-startup-7.4:/startup.1.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/log/php-fpm-7.4:/var/log/php:rw${MOUNT_OPTIONS}
  #     # Generic volumes
  #     - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
  #     - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
  #     - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  # php80:
  #   <<: *default-php
  #   image: devilbox/php-fpm:8.0-work-0.150
  #   hostname: php80
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.209
  #   volumes:
  #     # Specific volumes
  #     - ${DEVILBOX_PATH}/cfg/php-ini-8.0:/etc/php-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-fpm-8.0:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-startup-8.0:/startup.1.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/log/php-fpm-8.0:/var/log/php:rw${MOUNT_OPTIONS}
  #     # Generic volumes
  #     - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
  #     - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
  #     - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  # php81:
  #   <<: *default-php
  #   image: devilbox/php-fpm:8.1-work-0.150
  #   hostname: php81
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.210
  #   volumes:
  #     # Specific volumes
  #     - ${DEVILBOX_PATH}/cfg/php-ini-8.1:/etc/php-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-fpm-8.1:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/cfg/php-startup-8.1:/startup.1.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/log/php-fpm-8.1:/var/log/php:rw${MOUNT_OPTIONS}
  #     # Generic volumes
  #     - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
  #     - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
  #     - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}
  #     - ${HOST_PATH_SSH_DIR}:/home/devilbox/.ssh:ro${MOUNT_OPTIONS}

  php82:
    <<: *default-php
    image: devilbox/php-fpm:8.2-work-0.150
    hostname: php82
    networks:
      app_net:
        ipv4_address: 172.16.238.211
    volumes:
      # Specific volumes
      - ${DEVILBOX_PATH}/cfg/php-ini-8.2:/etc/php-custom.d:ro${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/cfg/php-fpm-8.2:/etc/php-fpm-custom.d:ro${MOUNT_OPTIONS}
      # - ${DEVILBOX_PATH}/cfg/php-startup-8.2:/startup.1.d:rw${MOUNT_OPTIONS}
      # Generic volumes
      - ${HOST_PATH_HTTPD_DATADIR}:/shared/httpd:rw${MOUNT_OPTIONS}
      - ${DEVILBOX_PATH}/supervisor:/etc/supervisor/custom.d:rw${MOUNT_OPTIONS}
      # - ${DEVILBOX_PATH}/autostart:/startup.2.d:rw${MOUNT_OPTIONS}
      - devilbox-mail:/var/mail:rw${MOUNT_OPTIONS}


  # -----------------------------------------------------------------------------------------------
  # Ngrok
  # -----------------------------------------------------------------------------------------------
  # ngrok:
  #   image: devilbox/ngrok:0.3
  #   hostname: ngrok
  #   environment:
  #     - HTTP_TUNNELS=${NGROK_HTTP_TUNNELS:-httpd:httpd:80}
  #     - AUTHTOKEN=${NGROK_AUTHTOKEN:-}
  #     - REGION=${NGROK_REGION:-us}
  #   ports:
  #     - "${LOCAL_LISTEN_ADDR}${HOST_PORT_NGROK:-4040}:4040"
  #   networks:
  #     app_net:
  #       ipv4_address: 172.16.238.202
  #   depends_on:
  #     - bind
  #     - php
  #     - httpd
